### ISSUE TITLE
Stopping or pausing countdown?

### ISSUE THREAD

**Issue by vuk-nikolic** [odyniec/jQuery-tinyTimer#2]
Hi, 

I might have missed this, but how do I stop a timer? Or pause it :)

Thanks for for building this tiny and awesome timer, cheers!

**Comment by odyniec** [comment]
I didn't have the time to document this yet, but it is implemented :) You need to get the tinyTimer object, which is attached to the DOM element as `.data('tinyTimer')`. You can then call its methods: `stop`, `pause`, `start`, and `resume`. Here's an example:

``` javascript
$('#timer').tinyTimer({ ... });

var tt = $('#timer').data('tinyTimer');
tt.pause();
tt.resume();
```

`stop` and `pause` do the same thing, they just stop the timer at its current value. `start` and `resume` turn it back on, but they work differently -- `resume` adjusts the end time to account for the time when the timer was paused, while `start` does not. For example -- if you set up a 30-second countdown, pause it at 00:25, keep it paused for 10 seconds, then call `resume`, it will continue from 00:25, but if you call `start`, it will continue from 00:15. I hope this explanation makes sense :)

**Comment by vuk-nikolic** [comment]
Awesome, thanks for the turbo fast reply.
I've tried it and it works!

(some times looking at the source would help :))

**Comment by n3g** [comment]
Hi,
First of all, great plugin! :)
I'm trying to use it with a pause/resume button, however I'm getting the same behavior with start() and resume(): they both resume with the time that has elapsed.
I'm using jquery 1.10.2 with the latest version of your plugin.
The code I have is:

```
var timer_paused = false;
...
function pause_resume_timer() {
    var tt = $('#timer').data('tinyTimer'); 

    if (timer_paused) {
        tt.resume();
        timer_paused = false;
    } else {
        tt.stop();
        timer_paused = true;
    }
    $("#pause_resume_icon").toggleClass("icon-pause icon-play");
}
...
<i onclick="pause_resume_timer()" id="pause_resume_icon" class="icon-pause"></i><span id="timer" style="position: absolute; position: relative; left: -68px;"></span>
```

Any help is appreciated :)
